### ISSUE TITLE
Opaque Error on Upload

### ISSUE THREAD

**Issue by anabranch** [databricks/sbt-databricks#35]
```sh
> package
[success] Total time: 0 s, completed Jul 5, 2016 8:42:53 AM
> dbcUpload
[trace] Stack trace suppressed: run last *:dbcUpload for the full output.
[error] (*:dbcUpload) org.apache.http.client.HttpResponseException: NoSuchElementException: cannot find node with id 1016978
[error] Total time: 0 s, completed Jul 5, 2016 8:42:55 AM
> last *:dbcDeploy
org.apache.http.client.HttpResponseException: NoSuchElementException: cannot find node with id 1016978
	at sbtdatabricks.DatabricksHttp.handleResponse(DatabricksHttp.scala:80)
	at sbtdatabricks.DatabricksHttp.fetchLibraries(DatabricksHttp.scala:132)
	at sbtdatabricks.DatabricksPlugin$$anonfun$dbcFetchLibraries$1.apply(DatabricksPlugin.scala:74)
	at sbtdatabricks.DatabricksPlugin$$anonfun$dbcFetchLibraries$1.apply(DatabricksPlugin.scala:73)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:dbcDeploy) org.apache.http.client.HttpResponseException: NoSuchElementException: cannot find node with id 1016978
```

No idea what the problem is from this. Is there somewhere that I can improve this error message?

**Comment by anabranch** [comment]
error seems to happen for any number of DBC commands - the end folder does exist but was changed from one to another.
